-- RMS-2001: Add revenue KPI summary table
-- Purpose: Persist aggregated revenue KPI metrics for Power BI consumption
-- Author: Data Engineering Team
-- Date: 2026-03-24

CREATE TABLE IF NOT EXISTS ANALYTICS.DWH.REVENUE_KPI_SUMMARY (
    ID              NUMBER AUTOINCREMENT PRIMARY KEY,
    REGION          VARCHAR(100)  NOT NULL,
    PRODUCT_LINE    VARCHAR(100)  NOT NULL,
    REVENUE_AMOUNT  FLOAT         NOT NULL,
    PERIOD_MONTH    DATE          NOT NULL,
    CURRENCY_CODE   VARCHAR(3)    NOT NULL DEFAULT 'BRL',
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Grant read access to BI role
GRANT SELECT ON TABLE ANALYTICS.DWH.REVENUE_KPI_SUMMARY TO ROLE BI_READ_ROLE;
